1.0/redo auth service local storage
neontribe/ARCVMarket pull request #128
Opened 2017-06-21 15:32 UTC by ob6160

It's not perfect but it will do the job for now.

I've made two preliminary tests, @charlesstrange2 some more need to be made, we should figure out which other scenarios we need to test for.

2017-06-21 15:57 UTC, charlesstrange2 requested changes
Awesome!
See changes though

2017-06-21 15:57 UTC, charlesstrange2 commented on src/main.js
> +
Spacing

2017-06-21 15:57 UTC, charlesstrange2 commented on src/services/netMgr.js
> +import Vue from 'vue';
Why include this? i don't think we use it in this file.

2017-06-21 15:57 UTC, charlesstrange2 commented on src/services/netMgr.js
> +
Spacing?

2017-06-21 15:58 UTC, ob6160 commented on src/services/netMgr.js
> +import Vue from 'vue';
whoops I left that in good catch

2017-06-21 15:59 UTC, ob6160 commented on src/services/netMgr.js
> +
I quite like the space here as those two are variable sets and the last one is a method call. Don't mind either way - your call.

2017-06-22 09:34 UTC, katjam approved these changes
@charlesstrange2 I had a few minor comments - but happy for you to merge this in. Looks good.

2017-06-22 09:34 UTC, katjam commented on src/services/netMgr.js
> + - event bus
Are these todos? It't really clear what this list is.

2017-06-22 09:34 UTC, katjam commented on src/services/netMgr.js
> +
I am with @charlesstrange2 on this one. Though not much of a leg to stand on - we have been sort of following 'standards' and the rest of the code isn't so gapp-y.

Happy to leave it and wait until we get a standards set agreed.

2017-06-22 09:34 UTC, katjam commented on src/services/netMgr.js
> +    if(parsedLocalToken) this.setToken(parsedLocalToken);
Up to @charlesstrange2 - another standards issue... inline if statement.

2017-06-22 09:48 UTC, charlesstrange2 approved these changes

2017-06-22 09:55 UTC, merged