1.1/271 dupe message
neontribe/ARCVMarket pull request #183
Opened 2017-07-21 12:55 UTC by katjam

2017-07-21 13:05 UTC, ob6160 requested changes

2017-07-21 13:05 UTC, ob6160 commented on src/components/Queue.vue
> +                    var message = this.queueSuccessMessage(val.sentData);
Do we really need this method anymore if it's just returning val.sentData.message?

2017-07-21 16:23 UTC, katjam commented on src/components/Queue.vue
> +                    var message = this.queueSuccessMessage(val.sentData);
Nope but we are doing a refactor. So taking one step at a time. These are the final hours!

2017-07-21 16:25 UTC, ob6160 commented on src/components/Queue.vue
> +                    var message = this.queueSuccessMessage(val.sentData);
ok! :)

2017-07-24 15:13 UTC, ob6160 commented on src/pages/Scan.vue
> -                this.sponsorCode = "";
Why were these two lines removed? They're causing all the tests to fail.

2017-07-24 15:39 UTC, ob6160 commented
This doesn't seem to be fully working - closing - will fix.

2017-07-24 15:39 UTC, closed without merging

2017-07-24 15:45 UTC, katjam commented on src/pages/Scan.vue
> -                this.sponsorCode = "";
Not sure. @alexalala Do you think that was a mistake?

2017-07-24 15:47 UTC, ob6160 commented on src/pages/Scan.vue
> +                            this.setMessage(response.error, constants.MESSAGE_ERROR);
Also the messages are part of the "response.data" object not the response itself.

2017-07-24 15:48 UTC, ob6160 commented on src/pages/Scan.vue
> -                this.sponsorCode = "";
They're pretty essential to the functioning of the scan page afaik.

2017-07-24 15:51 UTC, ob6160 commented on src/pages/Scan.vue
> +                this.setMessage(response.error, constants.MESSAGE_ERROR);
There is no response in scope here.

2017-07-24 16:17 UTC, alexalala commented on src/pages/Scan.vue
> -                this.sponsorCode = "";
@katjam @ob6160 quite possibly!!! Add them back in if they need to be :)

2017-07-25 08:16 UTC, alexalala commented on src/pages/Scan.vue
> -                this.sponsorCode = "";
@ob6160 yeah it was probably a mistake. As I said, add them back in if you need to